### ISSUE TITLE
Milestone 3 To Do

### ISSUE THREAD

**Issue by seshafi** [UBC-MDS/DSCI-522-2425-team35-Heart_disease_diagnostic_machine#22]
- [x] Make scripts (see other issue)
- [x] Quarto report (MAREK)
- [x] Update environment as needed (LONG)
- [x] Create list of feedback from milestone 1 & create issue (SARAH)
